Creating Array using Numpy

In [4]:
import numpy as np
x=np.array([1,2,3,4,5]) #passing list
print(x)
xType=type(x)
print(x, "is of data type ", xType)

[1 2 3 4 5]
[1 2 3 4 5] is of data type  <class 'numpy.ndarray'>


For Checking Time Consuming in List and Array , 
- Using **%timeit** (***gives time of execution in single line***) and **%%timeit**(***gives time of execution in whole program***)

In [9]:
# Runtime of List
%timeit [j**4 for j in range(1, 9)] #list comprehension

2.26 μs ± 253 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
# Runtime for Array
import numpy as np
%timeit np.arange(1,9)**4

The slowest run took 10.09 times longer than the fastest. This could mean that an intermediate result is being cached.
70.3 μs ± 40.6 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


**Numpy Array Creation**
- To create a NumPy Array,
    - should import as, **import numpy as np** 
    - you can use the function, **np.array()**. 
    - passing list inside **array()** function 

In [14]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]
