# **Array**

In [5]:
import numpy as np
# Defining list with some values
x=[1, 2, 3, 4]
print("List x=", x)
print("Type of x=", type(x))

# Converting List into Arrays
y=np.array(x)
print("Array y=", y)
print("Type of y=", type(y))

List x= [1, 2, 3, 4]
Type of x= <class 'list'>
Array y= [1 2 3 4]
Type of y= <class 'numpy.ndarray'>


In [7]:
# Directly passing list in an array function
x=np.array([1, 2, 3, 4])
print(x)
print("Array x=", x)
print("Type of x=", type(x))

[1 2 3 4]
Array x= [1 2 3 4]
Type of x= <class 'numpy.ndarray'>


**Displaying Array By Asking from the User**

In [13]:
emptyList=[]
size=int(input("Enter the Number of Element in An Array: "))
for i in range(1, size+1):
    element1=int(input(f"Enter Element No. {i}: "))
    emptyList.append(element1)
arrayDemo=np.array(emptyList)
print("Array=", arrayDemo)
print(type(arrayDemo))

Array= [9 8 7 6 5 4]
<class 'numpy.ndarray'>


**Types/Dimensions in An Array:** 
- **1-D Arrays:** [1 2 3 4 5]
- **2-D Arrays:** [[1 2 3 4 5]]
- **3-D Arrays:** [[[1 2 3 4 5]]]
- **Higher Dimensional Arrays**

In [15]:
oneDimensionalArray=np.array([1, 2, 3, 4])
print("One Dimensional Array=", oneDimensionalArray)
print("Dimension: ", oneDimensionalArray.ndim)

One Dimensional Array= [1 2 3 4]
Dimension:  1


In [16]:
twoDimensionalArray=np.array([[1, 2, 3], [4, 5, 6]])
print("Two Dimensional Array: ", twoDimensionalArray)
print("Dimension: ", twoDimensionalArray.ndim)

Two Dimensional Array:  [[1 2 3]
 [4 5 6]]
Dimension:  2


In [19]:
# Two-Dimensional Array
arr2=np.array([[1, 2, 3, 4], [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array=", arr2)
print("Dimension=", arr2.ndim)

Array= [[ 1  2  3  4]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension= 2


In [26]:
# Three Dimensional Array
arr3=np.array([[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]])
print("Array: \n", arr3)
print("Dimension: ", arr3.ndim)

Array: 
 [[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
Dimension:  3


**Higher Dimensional Array** 

In [28]:
arrHigh=np.array([1, 2, 3, 4], ndmin=10)
print("Array: \n", arrHigh)
print("Dimension: ", arrHigh.ndim)

Array: 
 [[[[[[[[[[1 2 3 4]]]]]]]]]]
Dimension:  10
