# **Special Types of Array (filled with specific value)**

- Array filled with 0's 
- Array filled with 1's
- Create an empty array
- An array with a range of elements 
- Array diagonal element filled with 1's
- Create an array with values that are spaced linearly in a specified interval. 

**Array Filled with 0's**

In [6]:
import numpy as np
arrZero=np.zeros(6) # For Single Dimensional Array
print(arrZero)
print("Dimension: ", arrZero.ndim)

[0. 0. 0. 0. 0. 0.]
Dimension:  1


In [10]:
import numpy as np 
# arrZero1=np.zeros(9)
arrZero2=np.zeros((3,5)) # For Two Dimensional Array
# 3 rows and 5 columns
print(arrZero2)
print("Dimension: ", arrZero2.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Dimension:  2


In [13]:
# For Three Dimensional Array 
import numpy as np
arrZero3=np.zeros((3, 3, 4))    # Form Three Dimensional Array
# 3 arrays with, 3 rows and 4 columns
print(arrZero3)
print("Dimension: ", arrZero3.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Dimension:  3


# **Array Filled with 1's**

In [15]:
# For Single Dimensional Array
import numpy as np
arr1=np.ones(6) # with 6 elements as 1
print(arr1)
print("Dimension of Array: ", arr1.ndim)

[1. 1. 1. 1. 1. 1.]
Dimension of Array:  1


In [20]:
# For Two Dimensional Array
import numpy as np 
arr2=np.ones((4, 5))  #with 4 rows and 5 columns as '1' element
print(arr2)
print("Dimension of Array: ", arr2.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Dimension of Array:  2


In [21]:
# For Three Dimensional Array 
import numpy as np 
arr3=np.ones((4, 5, 5)) #with 4 arrays, 5 rows and 5 columns as '1' element
print(arr3)
print("Dimension of Array: ", arr3.ndim)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
Dimension of Array:  3


# **Creating an Empty Array**

In [23]:
# Creating an Empty Array
import numpy as np
arrEmpty=np.empty(4)
print("Array: ", arrEmpty)
print("Dimension of Array: ", arrEmpty.ndim)

Array:  [0.00000000e+000 1.08057569e-311 1.08057569e-311 1.08057569e-311]
Dimension of Array:  1


In [26]:
# Creating an Empty Array of Multiple Dimension 
import numpy as np 
arrEmpty=np.empty((4, 2))
print("Array: \n", arrEmpty)
print("Dinemsion of Array: ", arrEmpty.ndim)

Array: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Dinemsion of Array:  2


In [27]:
# Creating an Array of Multiple Dimension 
import numpy as np
arrMulti=np.empty((4, 3, 2))
print("Array: \n", arrMulti)
print("Dimension of Array: ", arrMulti.ndim)

Array: 
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
Dimension of Array:  3


# **Array with a Range of Elements** 

In [29]:
import numpy as np 
arrayRange=np.arange(5)
print("Array: ", arrayRange)
print("Dimension: ", arrayRange.ndim)

Array:  [0 1 2 3 4]
Dimension:  1


In [44]:
# For Two Dimension 
import numpy as np 
# For Two Dimensional Array
arrayRange=np.arange(7).reshape(1, 7)
print("Array: ", arrayRange)
print("Dimension of Array: ", arrayRange.ndim)

Array:  [[0 1 2 3 4 5 6]]
Dimension of Array:  2


# **Array with Diagonal Elements filled with 1's**

In [47]:
import numpy as np
arrDig=np.eye(3)    #For Square Matrix, 3x3
print(arrDig)
print("Dimension: ", arrDig.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Dimension:  2


In [55]:
import numpy as np
arrDig=np.eye(3, 5)
print(arrDig)
print("Dimension: ", arrDig.ndim)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
Dimension:  2


# **Create an array with values that are spaced linearly in a specified interval**

In [57]:
# using linspace() function
import numpy as np
arrLinSpaced=np.linspace(0, 10, num=5)
print(arrLinSpaced)

[ 0.   2.5  5.   7.5 10. ]
