# **Creating Random Valued Arrays**

- **rand()** 
- **randn()** 
- **ranf()** 
- **randint():**

Using **rand()** Function:
- generates a random value between 0 to 1.

In [31]:
# For 1-Dimensional
import numpy as np
var=np.random.rand()    #values lie between 0 and 1
print(var)

0.8008575919068466


In [33]:
# For 2 Dimensional Array
import numpy as np 
var1=np.random.rand(2, 5)   #2 rows and 5 columns
print(var1)

[[0.11554803 0.11617193 0.37730884 0.17069061 0.91585219]
 [0.36342317 0.32835033 0.53274695 0.39170479 0.31926738]]


In [35]:
# For 3-D Array
import numpy as np 
var2=np.random.rand(2, 5, 3)   #2 rows, 5 columns and 3 depth
print(var2)

[[[0.88682635 0.05398946 0.86762467]
  [0.50531873 0.63296322 0.6224898 ]
  [0.20105921 0.71983662 0.453249  ]
  [0.78288932 0.86762422 0.35405583]
  [0.87866943 0.68782504 0.34723895]]

 [[0.4833939  0.51355893 0.35299863]
  [0.65141267 0.11206313 0.74065874]
  [0.5285425  0.92647862 0.62224993]
  [0.43941228 0.537127   0.51693606]
  [0.64006579 0.56573728 0.55877948]]]


Using **randn()** Function
- generates a random value close to 0.
- This may return positive or negative numbers as well. 

In [38]:
import numpy as np
var2=np.random.randn(8)
print(var2)

[ 0.22602046 -0.80434222  0.88432521  0.50249151 -0.26384089  0.59207128
  0.80403595 -1.2713137 ]


In [40]:
import numpy as np 
var2=np.random.randn(8, 2)  # 8 rows and 2 columns
print(var2)

[[-0.16441044 -0.00377695]
 [ 0.51062797 -0.21145151]
 [-0.22957719  0.71456414]
 [-2.14349728 -1.18794157]
 [-0.39628475 -0.03799573]
 [ 2.15179858  0.15525404]
 [ 0.71593419 -0.1914401 ]
 [ 0.18786165 -0.88279684]]


using **ranf()** Function: 
- for doing random sampling in numpy. 
- It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).

In [41]:
import numpy as np
var=np.random.ranf(6)
print(var)

[0.32660948 0.41567715 0.73456183 0.5276185  0.95930731 0.03030773]


using **randint()** Function: 
- generates a random number between a given range.
- provides random number between minimum and maximun number.
- Syntax: np.random.randint(minValue, maxValue, noOfValue)

In [42]:
import numpy as np
var=np.random.randint(1, 100, 6)  # 6 random values between 1 and 100
print(var)

[11 23 38 32 49 26]
