# **Data Types**

1. **bool_:** Boolean (True or False) stored as a byte
2. **int_:** Default integer type (same as C long; normally either int64 or int32)
3. **Intc:** Identical to C int (normally int32 or int64)
4. **Intp:** Integer used for indexing (same as C size t; normally either int32 or int64)
5. **int8:** Byte (-128 to 127)
6. **int16:** Integer (-32768 to 32767)
7. **int32:** Integer (-2147483648 to 2147483647)
8. **int64:** Integer (-9223372036854775808 to 9223372036954775808)
9. **uint8:** Unsigned integer (0 to 255)
10. **uint16:** Unsigned Integer (0 to 65535)
11. **uint32:** Unsigned Integer (0 to 4294967295)
12. **uint64:** Unsigned Integer (0 to 18446744073709551615)
13. **float_:** Shorthand for float64
14. **float16:** Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
15. **float32:** Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
16. **float64:** Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
17. **complex_:** Shorthand for complex128
18. **complex64:** Complex number, represented by 32-bit floats (real and imaginary components)
19. **complex128:** Complex number, represented by two 64-bit floats (real and imaginary components)


In [7]:
import numpy as np
var=np.array([1, 2, 3, 4])
print("Data Type: ", var.dtype)

y= np.array([11, 12, 13, 14, 112, 3123123, 1231, 231234123123123123, 12312312312312312])
print("Data Type: ", y.dtype)

str=np.array(["manish", 12, "is", "a", 12.342, "boy"])
print("Data Type: ", str.dtype)

Data Type:  int32
Data Type:  int64
Data Type:  <U32


# **Data Types as a Function**
- List of Characters that are used to represent dtype in Numpy: 
    - **i:** integer
    - **b:** boolean
    - **u:** unsigned integer
    - **f:** float
    - **c:** complex float
    - **m:** timedelta
    - **M:** datetime
    - **O:** object
    - **S:** string
    - **U:** Unicode String
    - **V:** Fixed Chunk of memory for other types (void)

In [9]:
x=np.array([1, 2, 3, 4])
print(x.dtype)

int32


**Converting int32 to int8**

In [16]:
x=np.array([1, 2, 3, 4], dtype=np.int8)
print(x.dtype)

int8


**Converting int to float**

In [17]:
x1=np.array([1, 2, 3, 4, 5], dtype='f')
print(x1)
print("Data Type: ", x1.dtype)

[1. 2. 3. 4. 5.]
Data Type:  float32


In [23]:
x1=np.array([1, 2, 3, 4, 5])
new=np.float32(x1)
print("Data Type: ", x1.dtype)
print(x1)

print("Data Type: ", new.dtype)
print(new)

Data Type:  int32
[1 2 3 4 5]
Data Type:  float32
[1. 2. 3. 4. 5.]


**Converting Float into Integer**

In [30]:
x2=np.array([1.0, 2.0, 3.0, 4.0, 5.0])
new1=np.int_(x2)
print("Data Type: ", x2.dtype)
print(x2)
print("Data Type: ", new1.dtype)
print(new1)

Data Type:  float64
[1. 2. 3. 4. 5.]
Data Type:  int32
[1 2 3 4 5]


**Directly Changing Data Type**

In [31]:
x3=np.array([1, 2, 3, 4, 5])
new1=x2.astype(float)
print(x3)
print("Data Type: ", x3.dtype)
print(new1)
print("Data Type: ", new1.dtype)

[1 2 3 4 5]
Data Type:  int32
[1. 2. 3. 4. 5.]
Data Type:  float64
