# **Shaping and Reshaping in Numpy Array**

**Shaping of Array**
- using **varName.shape**: gives the dimension of the matrix. 

In [3]:
import numpy as np 
var = np.array([[1, 2], [1, 2]])
print(var)
print("Order of Matrix:", var.shape)

[[1 2]
 [1 2]]
Order of Matrix: (2, 2)


In [4]:
import numpy as np
var=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var)
print("Order of Matrix: ", var.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Order of Matrix:  (3, 3)


In [7]:
import numpy as np
var1=np.array([1, 2, 3, 4], ndmin=4)
print(var1)
print("Order of Matrix: ", var1.shape)

[[[[1 2 3 4]]]]
Order of Matrix:  (1, 1, 1, 4)


**Reshaping of An Array:** 
- converting of one-dimensional array into multi-dimensional array and vice-versa. 
- can be done by using **varName.reshape(rowNo, colNo)** function.

In [22]:
import numpy as np
var2=np.array([1, 2, 3, 4, 5, 6])
print(var2)
print("Dimension of Array: ", var2.ndim)
print("Order of Matrix: ", var2.shape)
x=var2.reshape(2, 3)
print(x)
print("Dimension of Array: ", x.ndim)
print("Order of Matrix: ", x.shape)

[1 2 3 4 5 6]
Dimension of Array:  1
Order of Matrix:  (6,)
[[1 2 3]
 [4 5 6]]
Dimension of Array:  2
Order of Matrix:  (2, 3)


In [31]:
import numpy as np
var3=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(var3)
print("Dimension of Array: ", var3.ndim)
print("Order of Matrix: ", var3.shape)
x1=var3.reshape(2, 3, 2)    # 2 rows and 3 columns and 2 depth
print(x1)
print("Dimension of Array: ", x1.ndim)
print("Order of Matrix: ", x1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension of Array:  1
Order of Matrix:  (12,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension of Array:  3
Order of Matrix:  (2, 3, 2)


**Moving 3-Dimensional Array to 1-Dimensional Array**

In [33]:
import numpy as np
var3=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(var3)
print("Dimension of Array: ", var3.ndim)
print("Order of Matrix: ", var3.shape)
x1=var3.reshape(2, 3, 2)    # 2 rows and 3 columns and 2 depth
print(x1)
print("Dimension of Array: ", x1.ndim)
print("Order of Matrix: ", x1.shape)

# Moving 3 Dimensional Array to 1-Dimensional Array
dim1=x1.reshape(-1) # -1 will convert 3D array to 1D array
print(dim1)
print("Dimension of Array: ", dim1.ndim)
print("Order of Matrix: ", dim1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension of Array:  1
Order of Matrix:  (12,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension of Array:  3
Order of Matrix:  (2, 3, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension of Array:  1
Order of Matrix:  (12,)
