# **Arithmetic Operations in Numpy Array**

- (a+b) => np.add(a,b)
- (a-b) => np.subtract(a,b)
- (a*b) => np.multiply(a,b)
- (a/b) => np.divide(a,b)
- (a%b) => np.mod(a,b)
- (a**b) => np.power(a,b)
- (1/a) => np.reciprocal(a)

**Addition**

In [2]:
import numpy as np
var=np.array([1,2,3,4])
varAdd=var+3    #add 3 to each element of the array
print(varAdd)

[4 5 6 7]


In [5]:
import numpy as np
arr1=np.array([1, 2, 3, 4])
arr2=np.array([2, 4, 6, 8])
sum=np.add(arr1, arr2)
print("a = ", arr1)
print("b = ", arr2)
print("a + b = ", sum)

a =  [1 2 3 4]
b =  [2 4 6 8]
a + b =  [ 3  6  9 12]


**Subtract**

In [8]:
import numpy as np
arr1=np.array([1, 2, 3, 4])  
arr2=np.array([2, 4, 6, 8])
diff=np.subtract(arr2, arr1)
diff1=np.subtract(arr1, arr2)
print("a = ", arr1)
print("b = ", arr2)
print("b - a = ", diff)
print("a - b = ", diff1)

a =  [1 2 3 4]
b =  [2 4 6 8]
b - a =  [1 2 3 4]
a - b =  [-1 -2 -3 -4]


**Multiplication**

In [11]:
import numpy as np
arr1=np.array([1, 2, 3, 4])  
product=np.multiply(arr1, 4)
print("a = ", arr1)
print("a * b = ", product)

a =  [1 2 3 4]
a * b =  [ 4  8 12 16]


In [10]:
import numpy as np
arr1=np.array([1, 2, 3, 4])  
arr2=np.array([2, 4, 6, 8])
product=np.multiply(arr1, arr2)
print("a = ", arr1)
print("b = ", arr2)
print("a * b = ",product)

a =  [1 2 3 4]
b =  [2 4 6 8]
a * b =  [ 2  8 18 32]


**Division**

In [13]:
import numpy as np
arr1=np.array([5, 15, 25, 35])
quotient=np.divide(arr1, 5)
print("a = ", arr1)
print("a / 5 = ", quotient)

a =  [ 5 15 25 35]
a / 5 =  [1. 3. 5. 7.]


In [14]:
import numpy as np
arr1=np.array([25, 50, 75, 100])  
arr2=np.array([5, 10, 15, 20])
quotient=np.divide(arr1, arr2)
print("a = ", arr1)
print("b = ", arr2)
print("b / a = ", quotient)

a =  [ 25  50  75 100]
b =  [ 5 10 15 20]
b / a =  [5. 5. 5. 5.]


**Modulus**

In [15]:
import numpy as np
arr1=np.array([25, 35, 45, 55])  
arr2=np.array([2, 4, 6, 8])
modulo=np.mod(arr1, arr2)
print("a = ", arr1)
print("b = ", arr2)
print("a % b = ", modulo)

a =  [25 35 45 55]
b =  [2 4 6 8]
a % b =  [1 3 3 7]


**Power/Exponential**

In [16]:
import numpy as np
arr1=np.array([1, 2, 3, 4])  
exp=np.power(arr1, 4)
print("a = ", arr1)
print("a ^ 3 = ", exp)

a =  [1 2 3 4]
a ^ 3 =  [  1  16  81 256]


In [17]:
import numpy as np
arr1=np.array([1, 2, 3, 4])  
arr2=np.array([2, 4, 6, 8])
expo=np.power(arr2, arr1)
print("a = ", arr1)
print("b = ", arr2)
print("b ^ a = ", expo)

a =  [1 2 3 4]
b =  [2 4 6 8]
b ^ a =  [   2   16  216 4096]


**Reciprocal**

In [21]:
import numpy as np
arr1=np.array([1, 2, 3, 4])  
arr2=np.array([2, 4, 6, 8])
reciprocal1=np.reciprocal(arr1)
reciprocal2=np.reciprocal(arr2)
print("a = ", arr1)
print("b = ", arr2)
print("1 / a = ", reciprocal1)
print("1 / b = ", reciprocal2)

a =  [1 2 3 4]
b =  [2 4 6 8]
1 / a =  [1 0 0 0]
1 / b =  [0 0 0 0]


**For 2D Array**

In [24]:
import numpy as np 
arr1=np.array([[1, 2, 3], [4, 5, 6]])
arr2=np.array([[7, 8, 9], [10, 11, 12]])
sum=np.add(arr1, arr2)
print("a = ", arr1)
print("b = ", arr2)
print("a + b = ", sum)

a =  [[1 2 3]
 [4 5 6]]
b =  [[ 7  8  9]
 [10 11 12]]
a + b =  [[ 8 10 12]
 [14 16 18]]


In [27]:
import numpy as np 
arr1=np.array([[1, 2, 3], [4, 5, 6]])
arr2=np.array([[7, 8, 9], [10, 11, 12]])
diff=np.subtract(arr2, arr1)
print("a = ", arr1)
print("b = ", arr2)
print("b - a = ", diff)

a =  [[1 2 3]
 [4 5 6]]
b =  [[ 7  8  9]
 [10 11 12]]
b - a =  [[6 6 6]
 [6 6 6]]


In [28]:
import numpy as np 
arr1=np.array([[1, 2, 3], [4, 5, 6]])
arr2=np.array([[7, 8, 9], [10, 11, 12]])
product=np.multiply(arr1, arr2)
print("a = ", arr1)
print("b = ", arr2)
print("a * b = ", product)

a =  [[1 2 3]
 [4 5 6]]
b =  [[ 7  8  9]
 [10 11 12]]
a * b =  [[ 7 16 27]
 [40 55 72]]


In [30]:
import numpy as np 
arr1=np.array([[1, 2, 3], [4, 5, 6]])
arr2=np.array([[7, 8, 9], [10, 11, 12]])
quotient=np.divide(arr2, arr1)
print("a = ", arr1)
print("b = ", arr2)
print("b / a = ", quotient)

a =  [[1 2 3]
 [4 5 6]]
b =  [[ 7  8  9]
 [10 11 12]]
b / a =  [[7.  4.  3. ]
 [2.5 2.2 2. ]]
