# **Arithmetic Functions in NumPy**

**Arithmetic Functions in NumPy**
- np.min(x)
- np.max(x)
- np.argmin(x)
- np.sqrt(x)
- np.sin(x)
- np.cos(x)
- np.cumsum(x)

**np.min(x):** minimum element present in an array

In [11]:
import numpy as np
arr=np.array([11, 29, 13, 41, 15, 3, 25])
minElem=np.min(arr)
print(minElem, "is the minimum element in an array ", arr)

3 is the minimum element in an array  [11 29 13 41 15  3 25]


**np.max(x):** maximum element present in an array

In [5]:
import numpy as np
arr=np.array([11, 29, 13, 41, 15, 3, 25])
maxElem=np.max(arr)
print(maxElem, "is the maximum element in an array ", arr)

41 is the maximum element in an array  [11 29 13 41 15  3 25]


**np.argmin(x):** gives the position of minimum element. 

In [9]:
import numpy as np
arr=np.array([11, 29, 13, 41, 15, 3, 25])
minElem=np.min(arr)
minPos=np.argmin(arr)
print(minElem, "is the minimum element in an array ", arr, "at position ", (minPos+1))

3 is the minimum element in an array  [11 29 13 41 15  3 25] at position  6


In [16]:
import numpy as np
arr=np.array([[2, 4, 6, 8], [4, 8, 12, 16]])
minElem=np.min(arr)
minPos=np.argmin(arr)
print(minElem, "is the minimum element in an array ", arr, "at position ", (minPos+1))

2 is the minimum element in an array  [[ 2  4  6  8]
 [ 4  8 12 16]] at position  1


**np.argmax(x):** gives the position of maximum element.

In [13]:
import numpy as np
arr=np.array([11, 29, 13, 41, 15, 3, 25])
maxElem=np.max(arr)
maxPos=np.argmax(arr)
print(maxElem, "is the maximum element in an array ", arr, "at position ", (maxPos+1))

41 is the maximum element in an array  [11 29 13 41 15  3 25] at position  4


In [23]:
import numpy as np
arr=np.array([[2, 4, 6, 8], [4, 8, 12, 16]])
maxElem=np.max(arr)
maxPos=np.argmax(arr)
print(maxElem, "is the maximum element in an array ", arr, "at position ", (maxPos+1))

16 is the maximum element in an array  [[ 2  4  6  8]
 [ 4  8 12 16]] at position  8


**Note:**
- **For Column:** pass axis=0 
    - Example: 
    - np.min(arr, axis=0)   # determines minimum elements in Column
- **For Row:** pass axis=1
    - Example: 
    

**np.sqrt(x):** determines the square root of the entered number

In [27]:
import numpy as np
num=np.array([1, 4, 9, 16, 25, 36, 49, 64, 81, 100])
sqrt=np.sqrt(num)
print("Array: ", num)
print("Square Root of Array: ", sqrt)

Array:  [  1   4   9  16  25  36  49  64  81 100]
Square Root of Array:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [29]:
import numpy as np
num=np.array([[1, 4, 9], [16, 25, 36], [49, 64, 81]])
sqrt=np.sqrt(num)
print("Array: \n", num)
print("Square Root of Array: \n", sqrt)

Array: 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Square Root of Array: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


**np.sin(x):**
- gives the trigonometric sine value of each element in the array **x**. 
- The input to **np.sin(x)** should be in radians, not in degrees. 

**np.cos(x):**
- gives the trigonometric cosine value of each element in the array **x**. 
- The input to **np.cos(x)** should be in radians, not in degrees. 

In [43]:
import numpy as np
varDeg=np.array([30, 45, 60,  90])
varRad=np.radians(varDeg)
print("Array: ", np.round(varRad, 4))
print("Sine value : ", np.round(np.sin(varRad), 4))
print("Cosine value:", np.round(np.cos(varRad), 4))

Array:  [0.5236 0.7854 1.0472 1.5708]
Sine value :  [0.5    0.7071 0.866  1.    ]
Cosine value: [0.866  0.7071 0.5    0.    ]


In [34]:
import numpy as np
var2=np.array([0, np.pi/2, np.pi])
print("Array: ", var2)
print("Sine value : ", np.sin(var2))
print("Cosine value:", np.cos(var2))

Array:  [0.         1.57079633 3.14159265]
Sine value :  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine value: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [39]:
import numpy as np
# Values in Degrees
varDeg=np.array([0, 30, 45, 60, 90])
# Values in Radians
varRad=np.radians(varDeg)
print("Array: ", np.round(varRad, 3))
print("Sine value : ", np.round(np.sin(varRad), 3))
print("Cosine value:", np.round(np.cos(varRad), 3))

Array:  [0.    0.524 0.785 1.047 1.571]
Sine value :  [0.    0.5   0.707 0.866 1.   ]
Cosine value: [1.    0.866 0.707 0.5   0.   ]


**np.cumsum(x):** 
- finds out the culmulative sum of the elements along a given axis.
- **Syntax:** np.cumsum(x, axis=None, dtype=None, out=None)
- Here, except **x**, all are optional. 

In [49]:
import numpy as np 
arr=np.array([1, 2, 3, 4, 5])
cumSum=np.cumsum(arr)
print("Array: ", arr)
print("Culmulative Sum: ", cumSum)

Array:  [1 2 3 4 5]
Culmulative Sum:  [ 1  3  6 10 15]


In [48]:
# For 2D Array
arr=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
overallSum=np.cumsum(arr)
rowSum=np.cumsum(arr, axis=0)
colSum=np.cumsum(arr, axis=1)
print("Array: \n", arr)
print("Overall Culmulative Sum: \n", overallSum)
print("Culmulative Sum Along Rows: \n", rowSum)
print("Culmulative Sum Along Columns: \n", colSum)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Overall Culmulative Sum: 
 [ 1  3  6 10 15 21 28 36 45 55 66 78]
Culmulative Sum Along Rows: 
 [[ 1  2  3  4]
 [ 6  8 10 12]
 [15 18 21 24]]
Culmulative Sum Along Columns: 
 [[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]]
