# **Broadcasting NumPy Arrays**

- Dimension of matrices should be same. 
- Compatible if, 
    - Order of Both are equal 
    - Or one of them is 1

In [1]:
import numpy as np
arr1=np.array([1, 3, 5, 7, 9])
arr2=np.array([2, 4, 6])
sum=np.add(arr1, arr2)
print(sum)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [2]:
import numpy as np
arr1=np.array([1, 3, 5, 7, 9])
arr2=np.array([2, 4, 6, 8, 10])
sum=np.add(arr1, arr2)
print(sum)

[ 3  7 11 15 19]


In [7]:
import numpy as np
arr1=np.array([1, 2, 3])
arr1Shape=arr1.shape
print(arr1)
print(arr1Shape)
arr2=np.array([[1], [2], [3]])
arr2Shape=arr2.shape
print(arr2)
print(arr2Shape)
sum=np.add(arr1, arr2)
print(sum)

[1 2 3]
(3,)
[[1]
 [2]
 [3]]
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [2]:
import numpy as np
x=np.array([[1], [2]])
print(x)
print("Dimension of Array: ", x.shape)
y=np.array([[1, 2, 3], [1, 2, 3]])
print(y)
print("Dimension of Array: ", y.shape)

sum=np.add(x, y)
print("Sum=\n", sum)
print("Dimension of Array: ", sum.shape)

[[1]
 [2]]
Dimension of Array:  (2, 1)
[[1 2 3]
 [1 2 3]]
Dimension of Array:  (2, 3)
Sum=
 [[2 3 4]
 [3 4 5]]
Dimension of Array:  (2, 3)
