**Indexing NumPy Arrays**
>**Positive Indexing**

In [1]:
import numpy as np
oneDArray=np.array([10,20,30,40,50,60,70,80,90,100])
print(oneDArray)
print(oneDArray[0])
print(oneDArray[1])
print(oneDArray[2])
print(oneDArray[3])
print(oneDArray[4])
print(oneDArray[5])
print(oneDArray[6])
print(oneDArray[7])
print(oneDArray[8])
print(oneDArray[9])

[ 10  20  30  40  50  60  70  80  90 100]
10
20
30
40
50
60
70
80
90
100


>**Negative Indexing**

In [2]:
import numpy as np
oneDArray=np.array([10,20,30,40,50,60,70,80,90,100])
print(oneDArray)
print(oneDArray[-1])
print(oneDArray[-2])
print(oneDArray[-3])
print(oneDArray[-4])
print(oneDArray[-5])
print(oneDArray[-6])
print(oneDArray[-7])
print(oneDArray[-8])
print(oneDArray[-9])
print(oneDArray[-10])

[ 10  20  30  40  50  60  70  80  90 100]
100
90
80
70
60
50
40
30
20
10


In [51]:
import numpy as np
oneDArray=np.array([10,20,30,40,50,60,70,80,90,100])
print(oneDArray)
print("Dimension of Matrix: ", oneDArray.ndim)
print("Order of Matrix: ", oneDArray.shape)
print(oneDArray[0: 5])  # displays result excluding 5th positional element
print(oneDArray[0:])    # displays all the element in an array
print(oneDArray[:0])        #prints an empty array element
print(oneDArray[:]) #


[ 10  20  30  40  50  60  70  80  90 100]
Dimension of Matrix:  1
Order of Matrix:  (10,)
[10 20 30 40 50]
[ 10  20  30  40  50  60  70  80  90 100]
[]
[ 10  20  30  40  50  60  70  80  90 100]


In [47]:
import numpy as np
twoDArray=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(twoDArray)
print("Dimension of Matrix: ", twoDArray.ndim)
print("Order of Matrix: ", twoDArray.shape)
print(twoDArray[0]) #accessing 1st rows in matrix
print(twoDArray[2])     # accessing 2nd rows in matrix
print("Elements in First Row: ")
print(twoDArray[0][0])     #accessing 1st element of 1st row
print(twoDArray[0][1])  #accessing 2nd element of 1st row 
print(twoDArray[0][2])  # accessing 3rd element of 1st row 
print(twoDArray[0][3])  # accessing 4th element of 1st row
print(twoDArray[0][:])
print("Elements in Second Row: ")
print(twoDArray[1][0])  #accessing 1st element of 2nd row
print(twoDArray[1][1])  # accessing 2nd element of 2nd row
print(twoDArray[1][2])  # accessing 3rd element of 2nd row
print(twoDArray[1][3])  # accessing 4th element of 2nd row
print(twoDArray[1][:])
print("Elements in Third Row: ")
print(twoDArray[2][0])  # accessing 1st element of 3rd row
print(twoDArray[2][1])  # accessing 2nd element of 3rd row
print(twoDArray[2][2])  # accessing 3rd element of 3rd row
print(twoDArray[2][3])  # accessing 4th element of 3rd row
print(twoDArray[2][:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension of Matrix:  2
Order of Matrix:  (3, 4)
[1 2 3 4]
[ 9 10 11 12]
Elements in First Row: 
1
2
3
4
[1 2 3 4]
Elements in Second Row: 
5
6
7
8
[5 6 7 8]
Elements in Third Row: 
9
10
11
12
[ 9 10 11 12]


In [67]:
import numpy as np
twoDArray=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(twoDArray)
print("Dimension of Matrix: ", twoDArray.ndim)
print("Order of Matrix: ", twoDArray.shape)
print("Elements in Third Row: ", twoDArray[-1][:])
print(twoDArray[-1][-1])  # accessing last element of 3rd row
print(twoDArray[-1, -1])
print(twoDArray[-1][-2])    # accessing 2nd last element of 3rd row
print(twoDArray[-1, -2])
print(twoDArray[-1][-3])    # accessing 3rd last element of 3rd row
print(twoDArray[-1, -3])
print(twoDArray[-1][-4])    # accessing 1st element of 3rd row
print(twoDArray[-1, -4])
print("Elements in Second Row: ", twoDArray[-2][:])
print(twoDArray[-2][-1])    # accessing last element of 2nd row
print(twoDArray[-2, -1])
print(twoDArray[-2][-2])    # accessing 2nd last element of 2nd row
print(twoDArray[-2, -2])
print(twoDArray[-2][-3])    # accessing 3rd last element of 2nd row
print(twoDArray[-2, -3])
print(twoDArray[-2][-4])    # accessing 1st element of 2nd row
print(twoDArray[-2, -4])
print(twoDArray[-2, :])
print("Elements in First Row: ", twoDArray[-3][:])
print(twoDArray[-3][-1])    # accessing last element of 1st row
print(twoDArray[-3, -1])
print(twoDArray[-3][-2])    # accessing 2nd last element of 1st row
print(twoDArray[-3, -2])
print(twoDArray[-3][-3])    # accessing 3rd last element of 1st row
print(twoDArray[-3, -3])
print(twoDArray[-3][-4])   # accessing 1st element of 1st row
print(twoDArray[-3, -4])
print(twoDArray[-3, :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension of Matrix:  2
Order of Matrix:  (3, 4)
Elements in Third Row:  [ 9 10 11 12]
12
12
11
11
10
10
9
9
Elements in Second Row:  [5 6 7 8]
8
8
7
7
6
6
5
5
[5 6 7 8]
Elements in First Row:  [1 2 3 4]
4
4
3
3
2
2
1
1
[1 2 3 4]


In [56]:
var1=np.array([[9, 8, 7], [4, 5, 6]])
print(var1)
print("Dimension of Var1: ", var1.ndim)
print("Order of Var1: ", var1.shape)
print(var1[0, 2])

[[9 8 7]
 [4 5 6]]
Dimension of Var1:  2
Order of Var1:  (2, 3)
7


In [68]:
var2=np.array([[1, 2, 3], [4, 5, 6]])
print(var2)
print("Dimension: ", var2.ndim)
print("Order of Matrix: ", var2.shape)

[[1 2 3]
 [4 5 6]]
Dimension:  2
Order of Matrix:  (2, 3)


In [79]:
var3=np.array([[[1, 2], [3, 4]]])
print(var3)
print("Dimension: ", var3.ndim)
print("Order of Matrix: ", var3.shape)
print("Elements in 1st Row: ", var3[0, 0, :])
print(var3[0, 0, 0])
print(var3[0, 0, 1])
print("Elements in 2nd Row: ", var3[0, 1, :])
print(var3[0, 1, 0])
print(var3[0, 1, 1])

[[[1 2]
  [3 4]]]
Dimension:  3
Order of Matrix:  (1, 2, 2)
Elements in 1st Row:  [1 2]
1
2
Elements in 2nd Row:  [3 4]
3
4
