# **Slicing**
> arrName[start: stop: step]

In [15]:
import numpy as np
var=np.array([1, 2, 3, 4, 5, 6, 7])
print(var)
print("Dimension: ", var.ndim)
print("Order: ", var.shape)
print("Size: ", var.size)
print("Type: ", var.dtype)

# Slicing 
print('2 to 5', var[1:5])
print('2 to End: ', var[1:])
print("Start to 5: ", var[:5])
print("1 to 7, step 2", var[::2])
print("Stop: ", var[1::2])

[1 2 3 4 5 6 7]
Dimension:  1
Order:  (7,)
Size:  7
Type:  int32
2 to 5 [2 3 4 5]
2 to End:  [2 3 4 5 6 7]
Start to 5:  [1 2 3 4 5]
1 to 7, step 2 [1 3 5 7]
Stop:  [2 4 6]


**Slicing of 2-D Array**

In [28]:
twoDArray=np.array([[1, 2, 3, 4, 5], [9, 8, 7, 6, 5], [11, 12, 13, 14, 15]])
print(twoDArray)
print("Dimension: ", twoDArray.ndim)
print("Order: ", twoDArray.shape)
print("Size: ", twoDArray.size)

# Slicing Data
print("8 to 5: ", twoDArray[1, 1:])
print("8 to 5: ", twoDArray[-2, 1:])
print("8 to 5: ", twoDArray[-2, -4:])
print("12 to 15: ", twoDArray[2, 1:])
print("12 to 15: ", twoDArray[-1, 1:])
print("12 to 15: ", twoDArray[-1, -4:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]
Dimension:  2
Order:  (3, 5)
Size:  15
8 to 5:  [8 7 6 5]
8 to 5:  [8 7 6 5]
8 to 5:  [8 7 6 5]
12 to 15:  [12 13 14 15]
12 to 15:  [12 13 14 15]
12 to 15:  [12 13 14 15]
