# **Iterating NumPy Arrays**

In [3]:
import numpy as np
x=np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])
print("Dimension: ", x.ndim)
print("")
for i in x: 
    print (i)

9
8
7
6
5
4
3
2
1


In [17]:
y=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print("Dimension: ", y.ndim)
print("Order: ", y.shape)
print("Size: ", y.size)
for j in y:
    print(j)    # it prints only rows

Dimension:  2
Order:  (3, 5)
Size:  15
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [20]:
# Iterating element-wise
y=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(y)
print("Dimension: ", y.ndim)
print("Order: ", y.shape)
print("Size: ", y.size)

for k in y:
    for l in k:
        print(l)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimension:  2
Order:  (3, 5)
Size:  15
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [25]:
threeDArray=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Dimension: ", threeDArray.ndim)
print("Order: ", threeDArray.shape)
print("Size: ", threeDArray.size)
for i in threeDArray: 
    for j in i:
        for k in j:
            print(k)

Dimension:  3
Order:  (2, 2, 3)
Size:  12
1
2
3
4
5
6
7
8
9
10
11
12


**Iterating Alternative Way:** 
>Using **nditer()** function 

In [30]:
threeDArray=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(threeDArray)
print("Iterating with nditer()")
for i in np.nditer(threeDArray):
    print(i)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Iterating with nditer()
1
2
3
4
5
6
7
8
9
10
11
12


In [34]:
threeDArray=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(threeDArray)
print("Iterating with nditer()")
# for i in np.nditer(threeDArray, flags=['buffered'], op_dtypes=['S']):
for i in np.nditer(threeDArray):
    print(i)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Iterating with nditer()
1
2
3
4
5
6
7
8
9
10
11
12


**Iteration with Indexing**: using **ndenumerate()** function

In [37]:
threeDArray=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(threeDArray)
print("Iterating with nditer()")
# for i in np.nditer(threeDArray, flags=['buffered'], op_dtypes=['S']):
for i, d in np.ndenumerate(threeDArray):
    print(i, d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Iterating with nditer()
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12
