# **Join Functions in NumPy Array**

**Join Array:** Joining means putting contents of two or more arrays in a single array.

<div style="text-align: center;">
    <img src="./JoinArray.png" width= 100% height=100% alt="Centered Image">
</div>
<p style="text-align: center"><strong>Figure:</strong> Join Array in NumPy</p>

In [6]:
# Concatenating 1D Array
import numpy as np
var=np.array([1, 2, 3, 4])
var1=np.array([9, 8, 7, 6])
concat=np.concatenate((var, var1))
print(concat)

[1 2 3 4 9 8 7 6]


In [11]:
import numpy as np
vr=np.array([[1, 2], [3, 4]])
vr1=np.array([[5, 6], [7, 8]])
arrRow=np.concatenate((vr, vr1))
arrCol=np.concatenate((vr, vr1), axis=1)
print("Axis None or Axis Zero: \n",arrRow)
print("Axis 1: \n",arrCol)

Axis None or Axis Zero: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Axis 1: 
 [[1 2 5 6]
 [3 4 7 8]]


Using **np.stack((array1, array2), axis=___)**
- axis may be either 0 or 1
- 0 means row-wise and, 1 means columnwise

In [19]:
import numpy as np
arr1=np.array([[1, 2], [3, 4]])
arr2=np.array([[5, 6], [7, 8]])
res1=np.stack((arr1, arr2), axis=0)
print("With Axis=0")    #axis=0 means row wise
print(res1)
res2=np.stack((arr1, arr2), axis=1)
print("With Axis=1")    #axis=1 means column wise
print(res2)

With Axis=0
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
With Axis=1
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


**using np.hstack((var1, var2), axis=___)**
- merging the arrays along rows

In [18]:
var1=np.array([1, 2, 3, 4])
var2=np.array([9, 8, 7, 6])
aNew=np.stack((var1, var2), axis=0)
aNew1=np.hstack((var1, var2))
print(aNew)
print(aNew1)

[[1 2 3 4]
 [9 8 7 6]]
[1 2 3 4 9 8 7 6]


In [22]:
import numpy as np
arr1=np.array([[1, 2], [3, 4]])
arr2=np.array([[5, 6], [7, 8]])
res1=np.hstack((arr1, arr2))
print("With hstack")    #axis=0 means row wise
print(res1)

With hstack
[[1 2 5 6]
 [3 4 7 8]]


**using np.vstack((var1, var2), axis=___)**
- merging the arrays along colm

In [25]:
import numpy as np
arr1=np.array([[1, 2], [3, 4]])
arr2=np.array([[5, 6], [7, 8]])
res1=np.vstack((arr1, arr2))
print(arr1)
print(arr2)
print("With vstack")    #axis=0 means row wise
print(res1)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
With vstack
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**using np.hstack((var1, var2), axis=___)**
- merging the arrays along row-wise

In [26]:
arr1=np.array([1, 2, 3, 4])
arr2=np.array([9, 8, 7, 6])
combArray=np.hstack((arr1, arr2))
print(combArray)

[1 2 3 4 9 8 7 6]


In [29]:
arr1=np.array([[1, 2], [3, 4]])
arr2=np.array([[5, 6], [7, 8]])
combArray1=np.hstack((arr1, arr2))
print(combArray1)

[[1 2 5 6]
 [3 4 7 8]]


**using np.dstack((var1, var2), axis=___)**
- merging the arrays along height-wise

In [30]:
arr1=np.array([[1, 2], [3, 4]])
arr2=np.array([[5, 6], [7, 8]])
combArray1=np.dstack((arr1, arr2))
print(combArray1)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [36]:
var1=np.array([1, 2, 3, 4])
var2=np.array([9, 8, 7, 6])
aNew0=np.stack((var1, var2))
aNew=np.stack((var1, var2), axis=1)
aNew1=np.hstack((var1, var2))   # along row
aNew2=np.vstack((var1, var2))   # along column
aNew3=np.dstack((var1, var2))   #along height
print("np.stack")
print(aNew0)
print("np.stack with Axis 1")
print(aNew)
print("np.hstack")
print(aNew1)
print("np.vstack")
print(aNew2)
print("np.dstack")
print(aNew3)

np.stack
[[1 2 3 4]
 [9 8 7 6]]
np.stack with Axis 1
[[1 9]
 [2 8]
 [3 7]
 [4 6]]
np.hstack
[1 2 3 4 9 8 7 6]
np.vstack
[[1 2 3 4]
 [9 8 7 6]]
np.dstack
[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]
