**Split Array:** Splitting breaks one array into multiple
>**np.array_split(varName, n)**
- Where, ***n*** is the number of arrays you want to split into. 

In [16]:
import numpy as np
var=np.array([1, 2, 3, 4, 5, 6])
print(var)
print("Dimension: ",var.ndim)
print("Order: ", var.shape)
print("Size: ", var.size)
ar=np.array_split(var, 3)
print(ar)
print(type(ar))
print(ar[0])
print(ar[1])
print(ar[2])
print(ar[:])

[1 2 3 4 5 6]
Dimension:  1
Order:  (6,)
Size:  6
[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]
[3 4]
[5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [24]:
import numpy as np
var=np.array([[1, 2], [3, 4], [5, 6]])
print(var)
print("Dimension: ",var.ndim)
print("Order: ", var.shape)
print("Size: ", var.size)
ar=np.array_split(var, 3)
print(ar)
print(type(ar))
print(ar[0])
print(ar[1])
print(ar[2])
print(ar[:])

[[1 2]
 [3 4]
 [5 6]]
Dimension:  2
Order:  (3, 2)
Size:  6
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>
[[1 2]]
[[3 4]]
[[5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


also can be splitted through axis.

In [25]:
import numpy as np
var=np.array([[1, 2], [3, 4], [5, 6]])
print(var)
print("Dimension: ",var.ndim)
print("Order: ", var.shape)
print("Size: ", var.size)
ar=np.array_split(var, 3, axis=1)
print(ar)
print(type(ar))
print(ar[0])
print(ar[1])
print(ar[2])
print(ar[:])

[[1 2]
 [3 4]
 [5 6]]
Dimension:  2
Order:  (3, 2)
Size:  6
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
<class 'list'>
[[1]
 [3]
 [5]]
[[2]
 [4]
 [6]]
[]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
