**Sort Array:**
> - Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabet, ascending or descending. 
> - using **np.sort(varName)**

In [9]:
import numpy as np
var=np.array([4, 2, 3, 11, 17, 4,  1, 12, 5, 22, 52, 6, 7])
x=np.where((var%2)==0)
print(x)

(array([ 0,  1,  5,  7,  9, 10, 11], dtype=int64),)


In [10]:
print(np.sort(var))

[ 1  2  3  4  4  5  6  7 11 12 17 22 52]


In [11]:
var2=np.array(["a", "z", "u", "r", "e", "i", "s", "c", "l", "o", "u", "d"])
print(np.sort(var2))

['a' 'c' 'd' 'e' 'i' 'l' 'o' 'r' 's' 'u' 'u' 'z']


In [17]:
# Sorting 2D Array
arr=np.array([[9, 2, 1], [8, 6, 5], [7, 4, 3]])
print(arr)
arrSort=np.sort(arr)
print(arrSort)

[[9 2 1]
 [8 6 5]
 [7 4 3]]
[[1 2 9]
 [5 6 8]
 [3 4 7]]
