**Flatten And Ravel**
> - converting 2D array to 1D Array, giving orders
> - **Order: {'C', 'F', 'A', 'K'}, Optional**
>   - **'C':** means to flatten in row-major (C-style) order. 
>   - **'F':** means to flatten in column-major (Fortran-style) order. 
>   - **'A':** means to flatten in column-major order if 'a' is FORTRAN \*contiguous\* in memory, row-major order otherwise. 
>   - **'K':** means to flatten 'a' in the orde the elements occur in memory. 
>   - The default is 'C'

In [9]:
import numpy as np
var=np.array([1, 2, 3, 4, 5, 6])
print(var)
var2=np.resize(var, (2, 3))
print(var2)
print("C-Style")
var3=(var2.flatten(order='C'))
print(var3)
print("F-Style")
var3=(var2.flatten(order='F'))
print(var3)
print("A-Style")
var3=(var2.flatten(order='A'))
print(var3)
print("K-Style")
var3=(var2.flatten(order='K'))
print(var3)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
C-Style
[1 2 3 4 5 6]
F-Style
[1 4 2 5 3 6]
A-Style
[1 2 3 4 5 6]
K-Style
[1 2 3 4 5 6]


In [10]:
import numpy as np
var=np.array([1, 2, 3, 4, 5, 6])
print(var)
var2=np.resize(var, (2, 3))
print(var2)
print("C-Style")
var3=(var2.ravel(order='C'))
print(var3)
print("F-Style")
var3=(var2.ravel(order='F'))
print(var3)
print("A-Style")
var3=(var2.ravel(order='A'))
print(var3)
print("K-Style")
var3=(var2.ravel(order='K'))
print(var3)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
C-Style
[1 2 3 4 5 6]
F-Style
[1 4 2 5 3 6]
A-Style
[1 2 3 4 5 6]
K-Style
[1 2 3 4 5 6]
