**Insert and Delete Function**
> - inserting data in an array, Insert
>   - using, **np.insert(arrName, position, value)**
> - deleting data in an array, Delete
>   - using,

In [4]:
import numpy as np
var=np.array([1, 2, 3, 4, 5])
print(var)
print("Inserting 10 after 1")
var1=np.insert(var, 1, 10)   # pos=1 means 2nd position
print(var1)
print("Inserting 23 between 2 and 3")
var2=np.insert(var1, (2, 3), 23)
print(var2)

[1 2 3 4 5]
Inserting 10 after 1
[ 1 10  2  3  4  5]
Inserting 23 between 2 and 3
[ 1 10 23  2 23  3  4  5]


In [12]:
var1=np.array([[1,2, 3], [4, 5, 6]])
print(var1)
v=np.insert(var1, (2, 3), 6.5)
print(v)

[[1 2 3]
 [4 5 6]]
[1 2 6 3 6 4 5 6]


In [14]:
var1=np.array([[1,2, 3], [4, 5, 6]])
print(var1)
v=np.insert(var1, 2, 9, axis=1)
print(v)

[[1 2 3]
 [4 5 6]]
[[1 2 9 3]
 [4 5 9 6]]


In [17]:
var1=np.array([[1, 2, 3], [4, 5, 6]])
print(var1)
v=np.insert(var1, 2, [2, 9], axis=1)
print(v)

[[1 2 3]
 [4 5 6]]
[[1 2 2 3]
 [4 5 9 6]]


In [22]:
var1=np.array([[1, 2, 3], [4, 5, 6]])
print(var1)
v=np.append(var1, [2, 3])
print(v)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 2 3]


In [31]:
var1=np.array([[1, 2, 3], [4, 5, 6]])
print(var1)
v=np.append(var1, [[2, 3, 23]], axis=0)
print(v)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 2  3 23]]


**Delete**

In [37]:
import numpy as np
var1=np.array([1, 2, 3, 4])
print(var1)
varNew=np.delete(var1, 2)
print(varNew)

[1 2 3 4]
[1 2 4]
