# **Matrix in NumPy Arrays**

**Create Matrix in NumPy Array**

In [9]:
import numpy as np
matrix=np.matrix([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
print(matrix)
print(type(matrix))

[[1 2 3]
 [3 4 5]
 [5 6 7]]
<class 'numpy.matrix'>


In [8]:
var1=np.array([[1, 2, 3], [4, 5, 6]])
print(var1)
print(type(var1))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [11]:
# Adding two matrices
matrix1=np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2=np.matrix([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
sum=np.add(matrix1, matrix2)
print("Result: \n", sum)

Result: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [13]:
# Subtracting two matrices
matrix1=np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2=np.matrix([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
difference=np.subtract(matrix2, matrix1)
print("Result: \n", difference)

Result: 
 [[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]


In [15]:
# Multiplying two Matrices
matrix1=np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2=np.matrix([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
product=np.multiply(matrix1, matrix2)
print("Result: \n", product)

Result: 
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [16]:
# Dot Multiplication of Two Matrices
matrix1=np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2=np.matrix([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
product=np.dot(matrix1, matrix2)
print("Result: \n", product)

Result: 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
