# **Matrix Functions in NumPy Arrays**
> - Transpose
> - Swapaxes: swaps axis, row to column and column to rows
> - Inverse
> - Power
> - Determinate

**Transpose of Matrix**

In [5]:
import numpy as np
mat=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print("Transpose of Above Matrix is: ")
print(mat.T)
print(np.transpose(mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of Above Matrix is: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


**Swapaxes**

In [17]:
import numpy as np
mat=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print("Swapaxes of Above Matrix is: ")
print(np.swapaxes(mat, 0, 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Swapaxes of Above Matrix is: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


**Inverse**

In [21]:
import numpy as np
mat=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print("Inverse of Above Matrix is: ")
print(np.linalg.inv(mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Inverse of Above Matrix is: 
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


**Power**
- using, **np.linalg.matrix_power(arrName, n)**
    - When, n=0, gives identity matrix (diagonal matrix with 1)
    - When, n>0, power applies i.e, A^2=AxA
    - When, n<0, inverse applies

In [27]:
import numpy as np
mat=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print("Power of Above Matrix is: ")
# Power of A= A.A
print(np.linalg.matrix_power(mat, 2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Power of Above Matrix is: 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


**Determinate**

In [32]:
import numpy as np
mat=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print("Determinate of Above Matrix is: ")
# Power of A= A.A
print(np.linalg.det(mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinate of Above Matrix is: 
6.66133814775094e-16
